name: CI

on: [push]

jobs:
  sast_scan: 
    name: Run bandit Scan
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set uo python
        uses: actions/setup-python@v2
        with:
          phyton-version: 3.13

      - name: Install Bandit 
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r . json -o bandit-output.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: bandit-findings
          path: bandit-output.json
          

     
  
   
